# Generated by Django 5.0.4 on 2024-04-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multifactor_auth', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
